language: rust
dist: bionic

matrix:
  include:
  - rust: stable
  - rust: 1.34.0
  - rust: beta
  - rust: nightly

install:
- if [[ $TRAVIS_RUST_VERSION = stable ]]; then rustup component add rustfmt clippy; fi
- sudo apt update && sudo apt install libwebp-dev -y;
script:
- cargo test --all --features ""
- cargo test --all --features "libwebp-0_5"
- cargo test --all --features "libwebp-0_6"
- if [[ $TRAVIS_RUST_VERSION = nightly ]]; then cargo doc --all --features ""; fi
- if [[ $TRAVIS_RUST_VERSION = stable ]]; then cargo fmt --all -- --check; fi
